#Specs
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'Mirror-iOS_Example' do
  # pod 'Mirror-iOS', :path => '../'
  pod 'Mirror-iOS'

  target 'Mirror-iOS_Tests' do
    inherit! :search_paths

    
  end
end